//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.Racun_Korisnik = new HashSet<Racun_Korisnik>();
        }
    
        public int Id { get; set; }
        public string Ime_Prezime { get; set; }
        public string Adresa { get; set; }
        public string Mobitel { get; set; }
        public System.DateTime Datum_upisa { get; set; }
        public int Id_clanarine { get; set; }
    
        public virtual Clanarine Clanarine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun_Korisnik> Racun_Korisnik { get; set; }
    }
}
