//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun_Korisnik
    {
        public int Id { get; set; }
        public int Id_Korisnika { get; set; }
        public System.DateTime Datum_izdavanja { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
