//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun_Proizvodi
    {
        public int Id_racuna { get; set; }
        public int Id_proizvoda { get; set; }
        public int Kolicina { get; set; }
    
        public virtual Proizvodi Proizvodi { get; set; }
        public virtual Racuni Racuni { get; set; }
    }
}
